name: Build TypeDoc
on: [push]
jobs:
  build_typedoc:
    runs-on: ubuntu-latest
    name: Build TypeDoc
    steps:
    - uses: actions/checkout@v2
    - id: Build-TypeDoc
      uses: zakodium/typedoc-action@v2.8.0
      with:
        entry: 'src/main.ts'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
