name: Run tests
on:
  workflow_dispatch:
jobs:
  run_tests:
    runs-on: ubuntu-latest
    services:
      # https://github.com/orgs/community/discussions/42127#discussioncomment-7591609
      icinga:
        image: icinga/icinga2
        volumes:
          - /tmp/etc-icinga2:/data/etc/icinga2
        options: --name icinga

    steps:
    - uses: actions/checkout@v2
    - run: sudo rm -rf /tmp/etc-icinga2
    - run: sudo cp -fr resources/etc-icinga2 /tmp/etc-icinga2

    - name: Restart icinga
      uses: docker://docker
      with:
        args: docker restart icinga
