name: Run tests
on:
  workflow_dispatch:
jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Start docker container
      uses: docker://docker
      with:
        args: run --name icinga-master -v ./resources/etc-icinga2:/data/etc/icinga2 -h icinga-master -p 5665:5665 -e ICINGA_MASTER=1 -d icinga/icinga2
