name: Run tests
on: [push]

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: chmod -R 777 ./resources/etc-icinga2
    - name: Start docker container
      uses: docker://docker
      with:
        args: run --name icinga-master -v ${{ github.workspace }}/resources/etc-icinga2:/data/etc/icinga2 -h icinga-master -p 5665:5665 -e ICINGA_MASTER=1 -d icinga/icinga2

    - run: sleep 10

    - name: logs docker container
      uses: docker://docker
      with:
        args: logs icinga-master
